source 'https://rubygems.org'

gem 'rails', '~> 5.1.2'
gem 'mysql2'
gem 'puma',  '~> 3.7'

gem 'sass-rails', '~> 5.0'
gem 'uglifier',   '>= 1.3.0'
gem 'webpacker'
gem 'jbuilder',   '~> 2.5'

gem 'geocoder'
gem 'carrierwave'
gem 'rmagick'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen',      '>= 3.0.5', '< 3.2'

  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
end
